default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username:
  password:

development:
  <<: *default
  database: bsuir_labs_development

test:
  <<: *default
  database: bsuir_labs_test

production:
  <<: *default
  database: bsuir_labs_production
  username: bsuir_labs
  password: <%= ENV['BSUIR_LABS_DATABASE_PASSWORD'] %>
